sudo: true
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- 'pypy3'
env:
  global:
  - LD_LIBRARY_PATH=./libsecp256k1_ext/.libs
  - DYLD_FALLBACK_LIBRARY_PATH=./libsecp256k1_ext/.libs
  - LIB_DIR=./libsecp256k1_ext/.libs
  - INCLUDE_DIR=./libsecp256k1_ext/include
  - PYPI_USERNAME=Ofekmeister
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/python-dl
matrix:
  include:
  - os: osx
    language: generic
    osx_image: xcode7.1
    python: 2.7
    env:
    - TRAVIS_PYTHON_VERSION=2.7
  - os: osx
    language: generic
    osx_image: xcode7.1
    python: 3.5
    env:
    - TRAVIS_PYTHON_VERSION=3.5
  - os: osx
    language: generic
    osx_image: xcode7.1
    python: 3.6
    env:
    - NEED_SSL_FIX=true
    - TRAVIS_PYTHON_VERSION=3.6
  - os: linux
    language: python
    python: 3.5
    sudo: required
    services:
    - docker
    env:
    - BUILD_LINUX_WHEELS=1
addons:
  apt:
    packages:
    - git
    - libtool
    - autoconf
    - automake
    - pkg-config
    - libffi-dev
    - libgmp-dev
before_install:
- cd $HOME
- mkdir bin
- export PATH=$HOME/bin:$PATH
- "if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then deactivate && wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-5.7.1-beta-linux_x86_64-portable.tar.bz2 && tar -jxf pypy3.5-5.7.1-beta-linux_x86_64-portable.tar.bz2 && echo 'Setting up aliases...' && export PATH=$HOME/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/:$PATH && ln -s ~/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pypy3.5 ~/bin/python && echo 'Setting up pip...' && pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pypy -m ensurepip && ln -s ~/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pip3.5 ~/bin/pip ; fi"
- cd $TRAVIS_BUILD_DIR
- chmod +x .travis/prepare_windows_build.sh .travis/build_windows_wheels.sh
- .travis/prepare_windows_build.sh
- source .travis/install.sh
install:
- python setup.py install
script:
- mv coincurve _coincurve
- coverage run --parallel --include="*/site-packages/*.egg/coincurve/*" -m py.test
- mv _coincurve coincurve
- coverage combine
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x .travis/deploy.sh && chmod +x .travis/build-linux-wheels.sh && .travis/deploy.sh
  on:
    tags: true
