sudo: true
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
env:
  global:
  - LD_LIBRARY_PATH=./libsecp256k1_ext/.libs
  - DYLD_FALLBACK_LIBRARY_PATH=./libsecp256k1_ext/.libs
  - LIB_DIR=./libsecp256k1_ext/.libs
  - INCLUDE_DIR=./libsecp256k1_ext/include
  - WHEELBUILDER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - PYPI_USERNAME=Ofekmeister
  matrix:
  - BUNDLED=1
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/python-dl
matrix:
  include:
  - os: osx
    language: generic
    osx_image: xcode7.1
    python: 2.7
    env:
    - TRAVIS_PYTHON_VERSION=2.7
    - BUNDLED=1
  - os: osx
    language: generic
    osx_image: xcode7.1
    python: 3.4
    env:
    - TRAVIS_PYTHON_VERSION=3.4
    - BUNDLED=1
  - os: osx
    language: generic
    osx_image: xcode7.1
    python: 3.5
    env:
    - TRAVIS_PYTHON_VERSION=3.5
    - BUNDLED=1
  - os: osx
    language: generic
    osx_image: xcode7.1
    python: 3.6
    env:
    - NEED_SSL_FIX=true
    - TRAVIS_PYTHON_VERSION=3.6
    - BUNDLED=1
  - os: linux
    language: python
    python: 3.5
    sudo: required
    services:
    - docker
    env:
    - BUNDLED=1
    - BUILD_LINUX_WHEELS=1
before_install:
- sudo apt-get update
- sudo apt-get install -y git automake autoconf libtool pkg-config libffi-dev libgmp-dev mingw-w64
- source .travis/install.sh
install:
- python setup.py install
script:
- mv coincurve _coincurve
- coverage run --parallel --include="*/site-packages/*.egg/coincurve/*" -m py.test
- mv _coincurve coincurve
- coverage combine
after_success:
- coveralls
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x .travis/deploy.sh && chmod +x .travis/build-linux-wheels.sh && .travis/deploy.sh
  on:
    tags: true
